Auth/urls.py
from django.urls import path
from .views import *

app_name = "Auth"
urlpatterns = [
    path('users/login/', Login.as_view(), name='login'),
    path('logout/', Logout.as_view(), name='logout'),
    path('ChangePassword/', ChangePassword, name='ChangePassword'),
    path('AddNewUser/', create_user, name='create_user'),
    path('Users/', Users.as_view(), name='Users'),
    path('Users/<int:pk>/update/', UsersUpdate.as_view(), name='UsersUpdate'),
]

Core/urls.py
from django.urls import path 
from . import views

app_name = 'Core'
urlpatterns = [
    path('', views.Index, name='index'),
    path('systemInfoCreate/', views.SystemInfoCreate.as_view(), name='SystemInfoCreate'),
    path('ColorCreate/', views.ColorCreate.as_view(), name='ColorCreate'),
    path('ColorUpdate/<int:pk>/', views.ColorUpdate.as_view(), name='ColorUpdate'),
    path('ColorDelete/<int:pk>/', views.ColorDelete.as_view(), name='ColorDelete'),
    path('ColorList/', views.ColorList.as_view(), name='ColorList'),
    path('ExpensessTypeList/', views.ExpensessTypeList.as_view(), name='ExpensessTypeList'),
    path('ExpensessTypeCreate/', views.ExpensessTypeCreate.as_view(), name='ExpensessTypeCreate'),
    path('ExpensessTypeDelete/<int:pk>/', views.ExpensessTypeDelete.as_view(), name='ExpensessTypeDelete'),
    path('systemInfoUpdate/<int:pk>/', views.SystemInfoUpdate.as_view(), name='SystemInfoUpdate'),
    path('factory_search/', views.FactorySearch.as_view(), name='FactorySearch'),
    path('product_search/', views.ProductSearch.as_view(), name='ProductSearch'),
    path('ProductSearch_size/', views.ProductSearch_size.as_view(), name='ProductSearch_size'),
    path('seller_search/', views.SellerSearch.as_view(), name='SellerSearch'),
    path('worker_search/', views.WorkerSearch.as_view(), name='WorkerSearch'),
    path('invoice_search/', views.InvoiceSearch.as_view(), name='InvoiceSearch'),
    path('treasury_search/', views.TreasurySearch.as_view(), name='TreasurySearch'),
    path('sp_invoice_search/<int:type>/', views.SpInvoiceSearch.as_view(), name='SpInvoiceSearch'),
    path('sp_supplier_search/<int:type>/', views.SpSupplierSearch.as_view(), name='SpSupplierSearch'),
    path('seller_invoice_search/<int:type>/', views.SellerInvoiceSearch.as_view(), name='SellerInvoiceSearch'),
    path('client_invoice_search/<int:type>/', views.ClientInvoiceSearch.as_view(), name='ClientInvoiceSearch'),
    path('wool_supplier_search/', views.WoolSupplierSearch.as_view(), name='WoolSupplierSearch'),
    path('wool_search/', views.WoolSearch.as_view(), name='WoolSearch'),
    path('system_statistics/', views.SystemStatistics, name='system_statistics'),
    path('ExpensessDetail/', views.ExpensessDetail, name='ExpensessDetail'),
    path('ExpensessCreate/', views.ExpensessCreate, name='ExpensessCreate'),
    path('ExpensessDelete/<int:pk>/', views.ExpensessDelete.as_view(), name='ExpensessDelete'),
]

Invoices/urls.py
from django.urls import path 
from .views import *

app_name = 'Invoices'
urlpatterns = [
    path('InvoiceList/<int:type>/', InvoiceList.as_view(), name="InvoiceList"),
    path('InvoiceTrashList/<int:type>/', InvoiceTrashList.as_view(), name="InvoiceTrashList"),
    path('InvoiceCreate/<int:type>/', InvoiceCreate.as_view(), name="InvoiceCreate"),
    path('InvoiceUpdate/<int:pk>/', InvoiceUpdate.as_view(), name="InvoiceUpdate"),
    path('InvoiceSave/<int:pk>/', InvoiceSave.as_view(), name="InvoiceSave"),
    path('InvoiceClose/<int:pk>/', InvoiceClose.as_view(), name="InvoiceClose"),
    path('InvoiceBack/<int:pk>/', InvoiceBack.as_view(), name="InvoiceBack"),
    path('InvoiceRestore/<int:pk>/', InvoiceRestore.as_view(), name="InvoiceRestore"),
    path('InvoiceSuperDelete/<int:pk>/', InvoiceSuperDelete.as_view(), name="InvoiceSuperDelete"),
    path('InvoiceDelete/<int:pk>/', InvoiceDelete.as_view(), name="InvoiceDelete"),
    path('AllInvoiceDelete/', AllInvoiceDelete, name="AllInvoiceDelete"),
    path('InvoiceDetail/<int:pk>/', InvoiceDetail, name="InvoiceDetail"),
    path('AddProductInvoice/<int:pk>/', AddProductInvoice, name='AddProductInvoice'),
    path('get_item_price/', get_item_price, name='get_item_price'),
    path('InvoiceProductsUpdate/<int:pk>/<int:id>/', InvoiceProductsUpdate.as_view(), name='InvoiceProductsUpdate'),
    path('InvoiceProductsDelete/<int:pk>/<int:id>/', InvoiceProductsDelete.as_view(), name='InvoiceProductsDelete'),
    path('PrintInvoice/<int:id>/', PrintInvoice, name='PrintInvoice'),
    # path('InvoiceReturn/', InvoiceReturn, name='InvoiceReturn'),
    # path('InvoiceReturnProduct/', InvoiceReturnProduct, name='InvoiceReturnProduct'),
    # path('get_item_return_price/', get_item_return_price, name='get_item_return_price'),
    # path('ReturnProductInvoice/<int:pk>/', ReturnProductInvoice, name='ReturnProductInvoice'),
]

Products/urls.py
from django.urls import path
from .views import * 

app_name = 'Products'
urlpatterns = [
    path('list/', ProductList.as_view(), name="ProductList"),
    path('trach/', ProductTrachList.as_view(), name="ProductTrachList"),
    path('create/', ProductCreate.as_view(), name="ProductCreate"),
    path('update/<int:pk>', ProductUpdate.as_view(), name="ProductUpdate"),
    path('add_quantity/<int:pk>', AddProductQuantity.as_view(), name="AddProductQuantity"),
    path('minus_quantity/<int:pk>', MinusProductQuantity.as_view(), name="MinusProductQuantity"),
    path('delete/<int:pk>', ProductDelete.as_view(), name="ProductDelete"),
    path('restore/<int:pk>', ProductRestore.as_view(), name="ProductRestore"),
    path('superDelete/<int:pk>', ProductSuperDelete.as_view(), name="ProductSuperDelete"),
    path('details/<int:pk>', ProductDetails.as_view(), name="ProductDetails"),
    ######################################################################################
    path('seller_list/', SellerList.as_view(), name="SellerList"),
    path('seller_trash/', SellerTrashList.as_view(), name="SellerTrashList"),
    path('seller_create/', SellerCreate.as_view(), name="SellerCreate"),
    path('seller_update/<int:pk>', SellerUpdate.as_view(), name="SellerUpdate"),
    path('seller_paid_value/<int:pk>', PaidSellerValue.as_view(), name="PaidSellerValue"),
    path('seller_paid_value2/<int:pk>', PaidSellerValue2.as_view(), name="PaidSellerValue2"),
    path('seller_delete/<int:pk>', SellerDelete.as_view(), name="SellerDelete"),
    path('seller_restore/<int:pk>', SellerRestore.as_view(), name="SellerRestore"),
    path('seller_superDelete/<int:pk>', SellerSuperDelete.as_view(), name="SellerSuperDelete"),
    path('seller_details/<int:pk>', SellerDetails.as_view(), name="SellerDetails"),
    path('seller_print/<int:pk>', PrintSellerInvoicesDetails, name="PrintSellerInvoicesDetails"),
    path('seller_payment_delete/<int:id>', SellerPaymentDelete, name="SellerPaymentDelete"),
]

ZerOne/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from django.urls.conf import include
from django.conf.urls import url

urlpatterns = [
    path('01admin01/', admin.site.urls),
    path('admin/', include('Core.urls')),
    path('', include('Core.urls')),
    path('',include('Auth.urls')),
    path('factory/', include('Factories.urls')),
    path('product/', include('Products.urls')),
    path('worker/', include('Workers.urls')),
    path('treasury/', include('Treasury.urls')),
    path('wool/', include('Wool.urls')),
    path('invoices/',include('Invoices.urls'), ),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


Core/views.py
from audioop import reverse
from datetime import timedelta
from dateutil.relativedelta import relativedelta

from django.contrib.auth.decorators import login_required
from django.db.models import Sum, F
from django.shortcuts import redirect, render
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import *
from django.contrib import messages
from Core.forms import ColorForm, ExpensessTypeCreateForm, SystemInfoForm, ExpensessForm
from Core.models import SystemInformation
from Products.models import *
from Factories.models import Factory, Supplier
from Treasury.models import Treasury, TreasuryOperation
from Wool.models import Wool, WoolSupplier
from Workers.models import Worker
from Invoices.models import Invoice, InvoiceItem
from Core.models import *

from PIL import Image
from io import BytesIO
from django.core.files.uploadedfile import SimpleUploadedFile
# Create your views here.


@login_required(login_url='Auth:login')
def Index(request):
    modules = Modules.objects.all().last()
    today = datetime.now().date()
    return render(request, 'core/index.html', {'modules':modules, 'today': today})

class ExpensessTypeList(LoginRequiredMixin, ListView):
    login_url = '/auth/login/'
    model = ExpnsessType
    paginate_by = 12
    template_name = 'Core/expensses_type_list.html'
    
    def get_queryset(self):
        qureyset = self.model.objects.all().order_by('-id')
        return qureyset
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['type'] = 'list'
        context['title'] = 'قائمة البنود'
        context['icons'] = '<i class="fas fa-shapes"></i>'
        context['page'] = 'active'
        context['count'] = self.model.objects.all().count()
        return context
    
class ExpensessTypeCreate(LoginRequiredMixin, CreateView):
    login_url = ' /auth/login/'
    model = ExpnsessType
    template_name = 'forms/form_template.html'
    form_class = ExpensessTypeCreateForm
    success_url = reverse_lazy('Core:ExpensessTypeList')
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'اضافة نوع جديد'
        context['message'] = 'info'
        context['action_url'] = reverse_lazy('Core:ExpensessTypeCreate')
        return context
    
    def get_success_url(self):
        messages.success(self.request, "تم إضافة بند جديد  ", extra_tags="success")

        if self.request.POST.get('url'):
            return self.request.POST.get('url')
        else:
            return self.success_url


class ExpensessTypeDelete(LoginRequiredMixin, UpdateView):
    login_url = '/auth/login/'
    model = ExpnsessType
    form_class = ExpensessTypeCreateForm
    template_name = 'forms/form_template.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'حذف البند : ' + str(self.object.name)
        context['message'] = 'super_delete'
        context['action_url'] = reverse_lazy('Core:ExpensessTypeDelete', kwargs={'pk': self.object.id})
        return context

    def form_valid(self, form):
        messages.success(self.request, " تم حذف البند " +  " نهائيا بنجاح ", extra_tags="success")
        my_form = ExpnsessType.objects.get(id=self.kwargs['pk'])
        my_form.delete()
        return redirect('Core:ExpensessTypeList')


class ColorList(LoginRequiredMixin, ListView):
    login_url = '/auth/login/'
    model = Color
    paginate_by = 12
    template_name = 'Core/color_list.html'
    
    def get_queryset(self):
        qureyset = self.model.objects.all().order_by('-id')
        return qureyset
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['type'] = 'list'
        context['title'] = 'قائمة الالوان'
        context['icons'] = '<i class="fas fa-shapes"></i>'
        context['page'] = 'active'
        context['count'] = self.model.objects.all().count()
        return context
    
class ColorCreate(LoginRequiredMixin, CreateView):
    login_url = ' /auth/login/'
    model = Color
    template_name = 'forms/form_template.html'
    form_class = ColorForm
    success_url = reverse_lazy('Core:ColorList')
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'اضافة لون في النظام'
        context['message'] = 'info'
        context['action_url'] = reverse_lazy('Core:ColorCreate')
        return context
    
    def get_success_url(self):
        messages.success(self.request, "تم إضافة بيانات للنظام بنجاح", extra_tags="success")

        if self.request.POST.get('url'):
            return self.request.POST.get('url')
        else:
            return self.success_url
        
        
class ColorUpdate(LoginRequiredMixin, UpdateView):
    login_url = '/auth/login/'
    model = Color
    form_class = ColorForm
    template_name = 'forms/form_template.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'تعديل اللون: ' + str(self.object)
        context['message'] = 'update'
        context['action_url'] = reverse_lazy('Core:ColorUpdate', kwargs={'pk': self.object.id})
        return context
    
    def get_success_url(self):
        messages.success(self.request,  "تم تعديل اللون " + str(self.object) + " بنجاح ", extra_tags="success")
        if self.request.POST.get('url'):
            return self.request.POST.get('url')
        else:
            return self.success_url
    

class ColorDelete(LoginRequiredMixin, UpdateView):
    login_url = '/auth/login/'
    model = Color
    form_class = ColorForm
    template_name = 'forms/form_template.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'حذف اللون : ' + str(self.object.color_name)
        context['message'] = 'super_delete'
        context['action_url'] = reverse_lazy('Core:ColorDelete', kwargs={'pk': self.object.id})
        return context

    def form_valid(self, form):
        messages.success(self.request, " تم حذف اللون " + str(self.object) + " نهائيا بنجاح ", extra_tags="success")
        my_form = Color.objects.get(id=self.kwargs['pk'])
        my_form.delete()
        return redirect('Core:ColorList')
    
        
class SystemInfoCreate(LoginRequiredMixin, CreateView):
    login_url = '/auth/login/'
    model = SystemInformation
    template_name = 'forms/form_template.html'
    form_class = SystemInfoForm
    success_url = reverse_lazy('Core:index')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'بيانات النظام'
        context['message'] = 'info'
        context['action_url'] = reverse_lazy('Core:SystemInfoCreate')
        return context
    
        # return reverse('Core:index')
        
    def form_valid(self, form):
        form.save()
        obj = form.save(commit=False)
        info = SystemInformation.objects.get(id=obj.id)

        logo = info.logo
        if logo:
            # Read the binary data of the image file
            image_data = logo.read()
            # Open the image using PIL
            img = Image.open(BytesIO(image_data))
            # Check if the image format is not PNG
            if img.format != 'PNG':
                # Convert the image to PNG
                img = img.convert('RGBA')
                png_data = BytesIO()
                img.save(png_data, format='PNG')
                png_file = SimpleUploadedFile("logo.png", png_data.getvalue(), content_type="image/png")
                # Save the converted PNG image back to the model
                info.logo = png_file
                info.save()

        return redirect(self.get_success_url())
    
    
class SystemInfoUpdate(LoginRequiredMixin, UpdateView):
    login_url = '/auth/login/'
    model = SystemInformation
    template_name = 'forms/form_template.html'
    form_class = SystemInfoForm
    success_url = reverse_lazy('Core:index')
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'تعديل بيانات النظام'
        context['message'] = 'info'
        context['info_obj'] = self.object
        context['action_url'] = reverse_lazy('Core:SystemInfoUpdate',kwargs={'pk': self.object.id})
        return context
    
    def get_success_url(self):
        messages.success(self.request, " تم تعديل بيانات النظام بنجاح", extra_tags="success")

        if self.request.POST.get('url'):
            return self.request.POST.get('url')
        else:
            return self.success_url
        # return reverse('Core:index')

    def form_valid(self, form):
        form.save()
        obj = form.save(commit=False)
        info = SystemInformation.objects.get(id=obj.id)

        logo = info.logo
        if logo:
            # Read the binary data of the image file
            image_data = logo.read()
            # Open the image using PIL
            img = Image.open(BytesIO(image_data))
            # Check if the image format is not PNG
            if img.format != 'PNG':
                # Convert the image to PNG
                img = img.convert('RGBA')
                png_data = BytesIO()
                img.save(png_data, format='PNG')
                png_file = SimpleUploadedFile("logo.png", png_data.getvalue(), content_type="image/png")
                # Save the converted PNG image back to the model
                info.logo = png_file
                info.save()


Core/templates/components/footer.html
<footer class="footer">
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-6">
                <span style="font-size: larger">
                    <span>جميع الحقوق محفوظة © <a>ZerOne 2021</a></span>
                    <script>
                        if (new Date().getFullYear() !== 2021){
                            document.write('- ' + new Date().getFullYear())
                        }
                    </script>
                </span>
            </div>
            <div class="col-sm-6">
                <div class="text-sm-right d-none d-sm-block">
                    <span style="font-size: larger">.Designed &amp; Developed by ZerOne Team</span>
                </div>
            </div>
        </div>
    </div>
</footer>

Core/templates/components/header.html

<header id="page-topbar">
    <div class="navbar-header">
        <div class="d-flex">
            <!-- LOGO -->
            <div class="navbar-brand-box" style="background-color: #eaedef">
                <a href="/" class="logo logo-dark">
                    <span class="logo-sm">
                        <img src="/static/assets/images/new.png" alt="" height="30">
                    </span>
                    <span class="logo-lg">
                        <img src="/static/assets/images/home.png" alt="" height="30">
                    </span>
                </a>

                <a href="/" class="logo logo-light">
                    <span class="logo-sm">
                        <img src="/static/assets/images/1logo2.png" alt="" height="30">
                    </span>
                    <span class="logo-lg">
                        <img src="/static/assets/images/main_logo2.png" alt="" height="30">
                    </span>
                </a>
            </div>

            <button type="button" class="btn btn-sm px-3 font-size-16 header-item waves-effect" id="vertical-menu-btn">
                <i class="fa fa-fw fa-bars"></i>
            </button>
            
        </div>

        <div class="d-flex">

           <!-- Search -->
            {% if not modules.stop_date or modules.stop_date and today < modules.stop_date %}
            <div class="dropdown d-none d-lg-inline-block ml-1">
                <button type="button" class="btn header-item noti-icon waves-effect" data-toggle="modal" data-target="#search_modal">
                    <i class="bx bx-search-alt"></i>                
                </button>
            </div>

            <!-- full screen -->
            <div class="dropdown d-none d-lg-inline-block ml-1">
                <button type="button" class="btn header-item noti-icon waves-effect" data-toggle="fullscreen">
                    <i class="bx bx-fullscreen"></i>
                </button>
            </div>

            <!-- notifeaction item -->
            <div class="dropdown d-inline-block">
                <button type="button" class="btn header-item noti-icon waves-effect" id="page-header-notifications-dropdown"
                    data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    
                    
                    {% if notification_count %}
                        <i class="bx bx-bell bx-tada"></i>
                        <span class="badge badge-danger badge-pill">{{notification_count}}</span>
                    {% else %}
                        <i class="bx bx-bell "></i>    
                    {% endif %}
                        
                   
                </button>
                <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right p-0"
                    aria-labelledby="page-header-notifications-dropdown">

                    <!--<div data-simplebar style="max-height: 230px;">-->
                    {% if modules.invoice_active %}
                    {% if invoices_notify.count > 0 %}
                    <div class="p-3">
                        <div class="row align-items-center">
                            <div class="col">
                                <h6 class="m-0" key="t-notifications"> فواتير مفتوحة </h6>
                            </div>
                        </div>
                    </div>
                    <div data-simplebar style="max-height: 200px;">
                        
                        {% for x in invoices_notify %}
                            <a href="{% url 'Invoices:InvoiceDetail' x.id %}" target="_blank" class="text-reset notification-item">
                                <div class="media">
                                    <div class="avatar-xs mr-3">
                                        <span class="avatar-title bg-primary rounded-circle font-size-16">
                                            <i class='bx bx-bell bx-tada bx-sm'></i>
                                        </span>
                                    </div>
                                    <div class="media-body">
                                        <h6 class="mt-0 mb-1" key="t-your-order">
                                            {% if x.invoice_type == 1 %}
                                            فاتورة مبيعات
                                            {% elif x.invoice_type == 2 %}
                                            فاتورة مرتجع مبيعات
                                            {% else %}
                                            فاتورة قطاعي
                                            {% endif %}
                                            لم يتم حفظها بشكل مؤقت او بشكل نهائي
                                        </h6>
                                        <div class="font-size-12 text-muted">
                                            <p
                                            class="mb-1 badge badge-danger font-size-12" key="t-grammer">
                                            فاتورة رقم {{ x.id }}
                                            <p class="mb-1 badge badge-primary font-size-12"> <span key="t-min-ago">{{x.date|date:'Y-m-d'}}</span></p>
                                        </p>
                                        </div>
                                    </div>
                                </div>
                            </a>
                        {% endfor %}
                        
                    </div>
                    {% endif %}
                    {% endif %}

                    {% if modules.product_active %}
                    {% if products_notify.count > 0 %}
                    <div class="p-3">
                        <div class="row align-items-center">
                            <div class="col">
                                <h6 class="m-0" key="t-notifications"> منتجات سعر البيع أقل من التكلفة </h6>
                            </div>
                        </div>
                    </div>
                    <div data-simplebar style="max-height: 200px;">

                        {% for x in products_notify %}
                            <a href="{% url 'Products:ProductUpdate' x.id %}" data-toggle="modal" data-target="#action_modal" class="text-reset notification-item">
                                <div class="media">
                                    <div class="avatar-xs mr-3">
                                        <span class="avatar-title bg-primary rounded-circle font-size-16">
                                            <i class='bx bx-bell bx-tada bx-sm'></i>
                                        </span>
                                    </div>
                                    <div class="media-body">
                                        <h6 class="mt-0 mb-1" key="t-your-order">
                                            موديل {{ x.name }}
                                             تخسر في بيعه
                                        </h6>
                                        <div class="font-size-12 text-muted">
                                            <p
                                            class="mb-1 badge badge-danger font-size-12" key="t-grammer">
                                            سعر البيع {{ x.price }}
                                            <p class="mb-1 badge badge-primary font-size-12"><span key="t-min-ago">سعر التكلفة {{ x.cost }}</span></p>
                                        </p>
                                        </div>
                                    </div>
                                </div>
                            </a>
                        {% endfor %}

                    </div>
                    {% endif %}
                    {% endif %}
                    <!--</div>-->
                </div>
            </div>
            {% endif %}

            <!-- user item -->
            <div class="dropdown d-inline-block">
                <button type="button" class="btn header-item waves-effect" id="page-header-user-dropdown"
                    data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <img class="rounded-circle header-profile-user" src="/static/assets/images/user.png"
                        alt="Header Avatar">
                    <span class="d-none d-xl-inline-block ml-1" key="t-henry">{{request.user}}</span>
                    <i class="mdi mdi-chevron-down d-none d-xl-inline-block"></i>
                </button>
                <div class="dropdown-menu dropdown-menu-right">
                    <!-- item-->

                    {% if request.user.is_superuser %}
                    {% if info %}
                        {% for x in info %}
                            <a class="dropdown-item" data-toggle="modal" data-target="#action_modal" 
                            href="{% url 'Core:SystemInfoUpdate' x.id %}">
                                
                            <i class='bx bx-info-circle font-size-16 align-middle mr-1' ></i>
                                <span key="t-profile">بيانات النظام</span>
                            </a>
                        {% endfor %}
                    {% else %}
                        <a class="dropdown-item" data-toggle="modal" data-target="#action_modal" 
                        href="{% url 'Core:SystemInfoCreate'%}">
                            <i class="bx bx-user font-size-16 align-middle mr-1"></i> 
                            <span key="t-profile">بيانات النظام</span>
                        </a>
                    {% endif %}
                    {% endif %}

                    
                    <a class="dropdown-item d-block" href="{% url 'Auth:ChangePassword' %}" data-target="#action_modal" data-toggle="modal">
                        <i class="bx bx-wrench font-size-16 align-middle mr-1"></i>
                        <span key="t-settings">تغير كلمة المرور</span>
                    </a>

                    
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item text-danger" href="{% url 'Auth:logout'%}"><i class="bx bx-power-off font-size-16 align-middle mr-1 text-danger"></i> <span key="t-logout">تسجيل الخروج</span></a>
                </div>
            </div>

           

        </div>
    </div>
</header>

Core/templates/components/no_data.html
<div class="row">

    <div class="col-lg-12">
        <div class="text-center mb-5 mt-5">
            <h1 class="display-2 font-weight-medium">4<i class="bx bx-buoy bx-spin text-primary display-3"></i>4</h1>
            <h4 class="text-uppercase">لا توجد بيانات</h4>
            <div class="mt-3 text-center">
                <a class="btn btn-primary waves-effect waves-light" href="index.html">اضافة بيانات</a>
            </div>
        </div>
    </div>
</div>

<div class="row d-flex justify-content-center">
    <div class="col-lg-12 d-flex justify-content-center ">

        <img src="/static/assets/images/error-img.png" width="400px" height="188px" alt="" class="img-fluid" >

    </div>
</div>

Core/templates/components/paginator.html
<div class="row" style="width: 100%">
    <div class="col-lg-12 col-md-12 col-sm-12">
        <ul class="pagination pagination-rounded justify-content-center mt-1 mb-5">
            
            {% if page_obj.has_previous %}
                <li class="page-item">
                    <a href="?page={{page_obj.pervious_page_number}}" class="page-link"><i class="mdi mdi-chevron-right"></i></a>
                </li>
            {% else %}
                <li class="page-item disabled">
                    <a href="#" class="page-link"><i class="mdi mdi-chevron-right"></i></a>

                </li>    
            {% endif %}
                
            {% for i in paginator.page_range %}
                
                {% if page_obj.number == i %}
                    <li class="page-item active">
                        <a href="#" class="page-link">{{i}}</a>
                    </li>
                {% else %}
                    <li class="page-item">
                        <a href="?page={{i}}" class="page-link">{{i}}</a>
                    </li>
                {% endif %}     
            {% endfor %}
        
        
        {% if page_obj.has_next %}
                <li class="page-item">
                    <a href="?page={{page_obj.next_page_number}}" class="page-link"><i class="mdi mdi-chevron-left"></i></a>
                </li>
        {% else %}
            <li class="page-item disabled">
                <a href="#" class="page-link"><i class="mdi mdi-chevron-left"></i></a>
            </li>   
        {% endif %}

        </ul>
    </div>
</div>
<!-- end row -->