Auth/urls.py
from django.urls import path
from .views import *

app_name = "Auth"
urlpatterns = [
    path('users/login/', Login.as_view(), name='login'),
    path('logout/', Logout.as_view(), name='logout'),
    path('ChangePassword/', ChangePassword, name='ChangePassword'),
    path('AddNewUser/', create_user, name='create_user'),
    path('Users/', Users.as_view(), name='Users'),
    path('Users/<int:pk>/update/', UsersUpdate.as_view(), name='UsersUpdate'),
]

Core/urls.py
from django.urls import path 
from . import views

app_name = 'Core'
urlpatterns = [
    path('', views.Index, name='index'),
    path('systemInfoCreate/', views.SystemInfoCreate.as_view(), name='SystemInfoCreate'),
    path('ColorCreate/', views.ColorCreate.as_view(), name='ColorCreate'),
    path('ColorUpdate/<int:pk>/', views.ColorUpdate.as_view(), name='ColorUpdate'),
    path('ColorDelete/<int:pk>/', views.ColorDelete.as_view(), name='ColorDelete'),
    path('ColorList/', views.ColorList.as_view(), name='ColorList'),
    path('ExpensessTypeList/', views.ExpensessTypeList.as_view(), name='ExpensessTypeList'),
    path('ExpensessTypeCreate/', views.ExpensessTypeCreate.as_view(), name='ExpensessTypeCreate'),
    path('ExpensessTypeDelete/<int:pk>/', views.ExpensessTypeDelete.as_view(), name='ExpensessTypeDelete'),
    path('systemInfoUpdate/<int:pk>/', views.SystemInfoUpdate.as_view(), name='SystemInfoUpdate'),
    path('factory_search/', views.FactorySearch.as_view(), name='FactorySearch'),
    path('product_search/', views.ProductSearch.as_view(), name='ProductSearch'),
    path('ProductSearch_size/', views.ProductSearch_size.as_view(), name='ProductSearch_size'),
    path('seller_search/', views.SellerSearch.as_view(), name='SellerSearch'),
    path('worker_search/', views.WorkerSearch.as_view(), name='WorkerSearch'),
    path('invoice_search/', views.InvoiceSearch.as_view(), name='InvoiceSearch'),
    path('treasury_search/', views.TreasurySearch.as_view(), name='TreasurySearch'),
    path('sp_invoice_search/<int:type>/', views.SpInvoiceSearch.as_view(), name='SpInvoiceSearch'),
    path('sp_supplier_search/<int:type>/', views.SpSupplierSearch.as_view(), name='SpSupplierSearch'),
    path('seller_invoice_search/<int:type>/', views.SellerInvoiceSearch.as_view(), name='SellerInvoiceSearch'),
    path('client_invoice_search/<int:type>/', views.ClientInvoiceSearch.as_view(), name='ClientInvoiceSearch'),
    path('wool_supplier_search/', views.WoolSupplierSearch.as_view(), name='WoolSupplierSearch'),
    path('wool_search/', views.WoolSearch.as_view(), name='WoolSearch'),
    path('system_statistics/', views.SystemStatistics, name='system_statistics'),
    path('ExpensessDetail/', views.ExpensessDetail, name='ExpensessDetail'),
    path('ExpensessCreate/', views.ExpensessCreate, name='ExpensessCreate'),
    path('ExpensessDelete/<int:pk>/', views.ExpensessDelete.as_view(), name='ExpensessDelete'),
]

Workers/urls.py
from django.urls import path
from .views import * 

app_name = 'Workers'
urlpatterns = [
    path('worker_list/', WorkerList.as_view(), name="WorkerList"),
    path('details/<int:pk>', WorkerDetails.as_view(), name="WorkerDetails"),
    path('trach/',WorkerTrachList.as_view(), name="WorkerTrachList"),
    path('create/',WorkerCreate.as_view(), name="WorkerCreate"),
    path('update/<int:pk>',WorkerUpdate.as_view(), name="WorkerUpdate"),
    path('delete/<int:pk>',WorkerDelete.as_view(), name="WorkerDelete"),
    path('restore/<int:pk>',WorkerRestore.as_view(), name="WorkerRestore"),
    path('superDelete/<int:pk>',WorkerSuperDelete.as_view(), name="WorkerSuperDelete"),
    path('all/print/<int:pk>/', PrintWorkerAll, name="PrintWorkerAll"),

    path('detail/payment/<int:pk>/div/', WorkerPayment_div.as_view(), name="WorkerPayment_div"),
    path('payment/create/', WorkerPaymentCreate, name="WorkerPaymentCreate"),
    path('payment/delete/', WorkerPaymentDelete, name="WorkerPaymentDelete"),
    path('payment/print/<int:pk>/', PrintWorkerPayment, name="PrintWorkerPayment"),

    path('detail/attendance/<int:pk>/div/', WorkerAttendance_div.as_view(), name="WorkerAttendance_div"),
    path('create/attendnace', WorkerAttendanceCreate, name="WorkerAttendanceCreate"),
    path('delete/attendnace', WorkerAttendanceDelete, name="WorkerAttendanceDelete"),
    path('attendance/print/<int:pk>/', PrintWorkerAttendance, name="PrintWorkerAttendance"),

    path('detail/production/<int:pk>/div/', Worker_Production_div.as_view(), name="WorkerProductions_div"),
    path('create/workerProdduction', WorkerProductionCreate, name="WorkerProductionCreate"),
    path('delete/worker_production', WorkerProductionDelete, name="WorkerProductionDelete"),
    path('productions/print/<int:pk>/', PrintWorkerproductions, name="PrintWorkerproductions"),
]

ZerOne/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from django.urls.conf import include
from django.conf.urls import url

urlpatterns = [
    path('01admin01/', admin.site.urls),
    path('admin/', include('Core.urls')),
    path('', include('Core.urls')),
    path('',include('Auth.urls')),
    path('factory/', include('Factories.urls')),
    path('product/', include('Products.urls')),
    path('worker/', include('Workers.urls')),
    path('treasury/', include('Treasury.urls')),
    path('wool/', include('Wool.urls')),
    path('invoices/',include('Invoices.urls'), ),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


Workers/models.py
import django
from django.utils import timezone
from django.db import models

from Auth.models import User
from Products.models import Product

# Create your models here.

WORKER_TYPE = (
    (5, "عامل يوميه"),
    (6, "عامل انتاج"),
)

class Worker(models.Model):
    name = models.CharField(max_length=30, verbose_name="اسم العامل")
    image = models.ImageField(verbose_name="صورة العامل", null=True, blank=True)
    phone = models.IntegerField(null=True, blank=True, verbose_name="رقم الموبيل")
    worker_type = models.IntegerField(choices=WORKER_TYPE, null=True, verbose_name="نوع العامل")
    day_cost = models.FloatField(default=0, null=True, verbose_name="التكلفة (*حساب اليومية في حالة عامل اليومية *حساب القطعة في حالة عامل الانتاج)")
    deleted = models.BooleanField(default=False, verbose_name="حذف")
    
    def __str__(self):
        return self.name
    
    
HOUR_COUNT = (
    (6, "2"),
    (7, "3"),
    (8, "4"),
    (1, "6"),
    (2, "8"),
    (3, "12"),
    (4, "18"),
    (5, "غياب"),
)

class WorkerAttendance(models.Model):
    date = models.DateField(verbose_name="تاريخ الحضور", default=django.utils.timezone.now())
    day = models.CharField(max_length=30, verbose_name="اليوم")
    worker = models.ForeignKey(Worker, on_delete=models.CASCADE,verbose_name="العامل")    
    hour_count = models.IntegerField(choices=HOUR_COUNT, null=True, verbose_name="عدد الساعات")
    attend = models.BooleanField(default=0, verbose_name="حضر")
    admin = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, verbose_name="المسئول")
    
    def __str__(self):
        return self.worker.name
    
class WorkerPayment(models.Model):
    created = models.DateTimeField(auto_now_add=True, verbose_name="تاريخ الاضافة")
    date = models.DateField(verbose_name="تاريخ السحب", default=django.utils.timezone.now())
    worker = models.ForeignKey(Worker, on_delete=models.CASCADE, verbose_name=" العامل") 
    price = models.FloatField(verbose_name="المبلغ")
    description = models.CharField(max_length=250, blank=True, null=True, verbose_name="وصف")
    admin = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, verbose_name="المسئول")

    def __str__(self):
        return self.worker.name

class WorkerProduction(models.Model):
    date = models.DateField(verbose_name="تاريخ الاستلام", default=django.utils.timezone.now())
    day = models.CharField(max_length=30, verbose_name="اليوم")
    worker = models.ForeignKey(Worker, on_delete=models.CASCADE, verbose_name="العامل")
    quantity = models.FloatField(default=0, verbose_name="الكمية بالقطعة")
    price = models.FloatField(default=0, verbose_name="فئة السعر")
    total = models.FloatField(default=0, verbose_name="الإجمالي")
    product = models.ForeignKey(Product, on_delete=models.SET_NULL, verbose_name="المنتج", null=True, blank=True)
    admin = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, verbose_name="المسئول")
    
    def __str__(self):
        return self.worker.name

Workers/forms.py
from django import forms
from .models import *

class WorkerForm(forms.ModelForm):
    class Meta:
        model = Worker
        exclude = ['deleted']
        widgets = {
            'name' : forms.TextInput(attrs={'class':'form-control' , }),
            'image' : forms.FileInput(attrs={'class':'form-control'}),
            'phone' : forms.TextInput(attrs={'class':'form-control'}),
            'work_type' : forms.Select(attrs={'class':'form-control'}),
            'day_cost' : forms.NumberInput(attrs={'class':'form-control', 'min':0}),
        }
        

class WorkerDeleteForm(forms.ModelForm):
    class Meta:
        fields = ['deleted']
        model = Worker
        widgets = {
            'deleted' : forms.HiddenInput()
        }        
                
        
class WorkerPaymentForm(forms.ModelForm):
    class Meta:
        fields = ['date', 'price', 'worker', 'description']
        model = WorkerPayment
        widgets = {
            'date' : forms.DateInput(attrs={'type':'date', 'class':'form-control',
            'placeholder':'تاريخ السحب...', 'id':'date'}),
            'price' : forms.NumberInput(attrs={ 'class':'form-control',
            'placeholder':'المبلغ...', 'id':'price'}),
            'description': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'وصف...', 'id': 'description'}),
        }
        
class WorkerPaymentReportForm(forms.Form):
    from_date = forms.DateField(required=False ,widget=forms.DateInput(attrs={
        'type':'date',
        'name':'from',
        'id':'from_date',
        'class':'form-control',
        'placeholder':'من ...'}),                       
        label= 'من',
        )
         
    to_date = forms.DateField(required=False ,widget=forms.DateInput(attrs={
        'type':'date',
        'name':'to_date',
        'id':'to_date',
        'class':'form-control',
        'placeholder':'الي ...'}),
        label= 'الي',
        )     


class WorkerAttendanceForm(forms.ModelForm):
    class Meta:
        fields = ['date', 'day', 'hour_count']
        model = WorkerAttendance
        widgets = {
            'date' :  forms.DateInput(attrs={'type':'date', 'class':'form-control',
            'placeholder':'تاريخ السحب...', 'id':'date_att'}),
            'day': forms.TextInput(attrs={'class': 'form-control',
                                           'placeholder': 'اليوم...', 'id': 'day_att', 'readonly':'readonly'}),
            'hour_count' : forms.Select(attrs={'class':'form-control',
            'placeholder':'عدد الساعات...', 'id':'hours_count'}),
        }
        
 
 
class WorkerProductionForm(forms.ModelForm):
    class Meta:
        fields = ['date', 'day', 'quantity', 'price', 'total', 'product']
        model = WorkerProduction
        widgets = {
            'date' : forms.DateInput(attrs={'type':'date', 'class':'form-control',
            'placeholder':'تاريخ الاستلام', 'id':'production_date'}),
            'day': forms.DateInput(attrs={'class': 'form-control',
                                           'placeholder': 'اليوم...', 'id': 'production_day', 'readonly':'readonly'}),
            'quantity' : forms.NumberInput(attrs={ 'class':'form-control', 'placeholder':'الكمية...',
            'id':'worker_quantity'}),
            'price': forms.NumberInput(attrs={'class': 'form-control', 'placeholder': 'السعر...',
                                                 'id': 'worker_price'}),
            'total': forms.NumberInput(attrs={'class': 'form-control', 'placeholder': 'الإجمالي...',
                                              'id': 'worker_total', 'readonly':'readonly'}),
            'product': forms.Select(attrs={'class': 'form-control', 'placeholder': ' المنتج...', 'id': 'worker_production'}),
        }

Workers/templates/Worker/worker_list.html
{% extends "base.html" %}
{% block title %}
<title>قائمة العمال</title>

{% endblock title %}

{% block main %}
    <div class="main-content">

      <div class="page-content">
          <div class="container-fuild">
           
                <div class="row">
                    <div class="col-12"> {% if messages %}
                        {% for message in messages %}
                        <div class="alert alert-{{ message.tags }} alert-dismissible fade show text-center" role="alert">
                            <i class="mdi mdi-check-all mr-2"></i>
                            {{ message|safe }}
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <span aria-hidden="true">×</span>
                            </button>
                        </div>
                        {% endfor %}

            
                      {% endif %}
                    </div>
                   
                </div>
              
                <div class="row">
                    <div class="col-12">
                        <div class="page-title-box d-flex align-items-center justify-content-between">
                            
                            {% if type == "list" %}
                                <h4 class="mb-0"> قائمة العمال
                                    <a class="badge badge-success" style="font-size:small;" href="{% url 'Workers:WorkerCreate' %}" data-toggle="modal" data-target="#action_modal">
                                            <i class="fas fa-plus-square fx-2"></i>
                                    </a>

                                    <a class="badge badge-info" style="font-size:small;" href="{% url 'Workers:WorkerList' %}">
                                       <i class="fas fa-list-ul"></i>
                                    </a>
                                     
                                    <a  class="badge badge-danger" style="font-size:small;" href="{% url 'Workers:WorkerTrachList' %}">
                                            <i class="fas fa-trash"></i>
                                    </a>
                                     
                                 </h4>
                                
                                {% else %}
                                <h4 class="mb-0"> سلة مهملات العمال
                                    <a class="badge badge-success" style="font-size:small;" href="{% url 'Workers:WorkerCreate' %}" data-toggle="modal" data-target="#action_modal">
                                            <i class="fas fa-plus-square fx-2"></i>
                                    </a>

                                    <a class="badge badge-info" style="font-size:small;" href="{% url 'Workers:WorkerList' %}">
                                       <i class="fas fa-list-ul"></i>
                                    </a>
                                     
                                    <a  class="badge badge-danger" style="font-size:small;" href="{% url 'Workers:WorkerTrachList' %}">
                                            <i class="fas fa-trash"></i>
                                    </a>
                                     
                                 </h4>
                            
                            {% endif %}
                            
                             
                            
                                <span class="badge badge-dark font-size-15"> الاجمالي : {{count}} عامل </span>
                               

                           
                            <div class="page-title-right">
                                <ol class="breadcrumb m-0">
                                    <li class="breadcrumb-item"><a href="/">الرئيسية</a></li>

                                    {% if type == "list" %}
                                    <li class="breadcrumb-item active">قائمة العمال</li>
                                    {% else %}
                                    <li class="breadcrumb-item active">قائمة العمال المحذوفة</li>
                                    {% endif %}
                                </ol>
                            </div>

                        </div>
                    </div>
                </div>

                {% if object_list %}
                <div class="row">
                    <div class="col-lg-3"></div>
                    <div class="col-lg-3"></div>
                    <div class="col-lg-3"></div>
                    <div class="col-lg-3">
                        {% if type == "list" %}
                        <form class="app-search d-none d-lg-block" method="get" action="{% url 'Core:WorkerSearch' %}">
                            <div class="position-relative" >

                                <input type="text" style="background-color: white" value="{{worker_serach}}" list="work" autocomplete="off" class="form-control" name="worker" placeholder="بحث ... بإسم العامل">
                                <span >
                                    <button class="bx bx-search-alt btn btn-warning" type="submit">
                                    </button>
                                </span>
                                <datalist id="work" >
                                    {% for pro in workers %}
                                        <option value="{{ pro.name }}">
                                            {{ pro.name }}
                                            </option>
                                    {% endfor %}
                                </datalist>
                            </div>
                        </form>
                        {% endif %}
                    </div>
                </div>
                <div class="row">
                {% for x in object_list  %}
                <div class="col-xl-3 col-md-4 col-sm-6">
                    <div class="card text-center">
                        <div class="card-body">
                            <div class="">
                                {% if x.image %}
                                <img class="rounded-circle avatar-xl" src="{{x.image.url}}" alt="" width="150px" height="180px">
                                {% else %}
                                <img class="rounded-circle avatar-xl" src="/static/assets/images/vector/worker2.png" alt="" width="150px">
                                {% endif %}

                            </div>
                            <h3><a href="{% url 'Workers:WorkerDetails' x.id %}" class="text-dark">{{x.name}}</a></h3>
                            <p class="text-muted">{{x.get_worker_type_display}}</p>

                            <div style="margin-top: 5px;">
                                <ul class="list-inline mb-0">
                                    <li class="list-inline-item mr-1">
                                        <div>
                                            <a href="{% url 'Workers:WorkerDetails' x.id %}" data-original-title="Message">
                                                <span class="badge badge-primary"  style="padding: 5px; font-size: 14px"><i class="fas fa-hand-holding-usd"></i>تفاصيل العامل</span>
                                            </a>
                                        </div>
                                    </li>

                                    <li class="list-inline-item mr-1">
                                        <div>
                                            <a href="{% url 'Workers:PrintWorkerAll' x.id %}" target="_blank">
                                               <span class="badge badge-secondary" style="padding: 5px; font-size: 14px"> <i class="fas fa-print"></i>كشف حساب</span>
                                            </a>
                                        </div>
                                    </li>
                                </ul>
                                

                            </div>
                        </div>
                        {% comment %} footer {% endcomment %}
                        <div class="card-footer bg-transparent border-top">
                            <div class="contact-links d-flex justify-content-center font-size-20">
                              {% if request.user.is_superuser %}
                              {% if type == "list"  %}
  
                              <div class="mr-3">
                                   <a href="{% url 'Workers:WorkerUpdate' x.id %}" data-toggle="modal" data-target="#action_modal" data-placement="top" title="" data-original-title="Message">
                                       <span class="badge  badge-info"><i class='bx bx-edit' ></i>تعديل</span>
                                  </a>
                               </div>
      
                              <div class="">
                                  <a href="{% url 'Workers:WorkerDelete' x.id %}" data-toggle="modal" data-target="#action_modal" data-placement="top" title="" data-original-title="Profile">
                                      <span class="badge  badge-danger"><i class='bx bxs-trash'  ></i>حذف</span>
                                  </a>
                              </div>
                          {% else %}
                               <div class="mr-3">
                                      <a href="{% url 'Workers:WorkerRestore' x.id %}" data-toggle="modal" data-target="#action_modal" data-placement="top" title="" data-original-title="Message">
                                          <span class="badge badge-dark"><i class='bx bx-redo '></i> استرجاع
                                          </span>
                                      </a>
                              </div>
  
                              <div class="">
                                  <a href="{% url 'Workers:WorkerSuperDelete' x.id %}" data-toggle="modal" data-target="#action_modal" data-placement="top" title="" data-original-title="Profile">
                                      <span class="badge badge-danger"><i class='bx bxs-trash '   ></i> حذف نهائي </span>
                                       
                                  </a>
                              </div>
                          {% endif %}
                              {% endif %}
                                
                              </div>
                        </div>
                    </div>
                </div>
                {% endfor %}


                </div>

                {% if is_paginated %}
                {% include "components/paginator.html" %}
                {% endif %}

                {% else %}

                <div class="row">

                    <div class="col-lg-12">
                        <div class="text-center mb-5 mt-5">
                            <h1 class="display-2 font-weight-medium">4<i class="bx bx-buoy bx-spin text-primary display-3"></i>4</h1>
                            {% if type == "list" %}
                            <h4 class="text-uppercase">لا توجد بيانات</h4>
                            {% else %}
                            <h4 class="text-uppercase">لا توجد بيانات محذوفة</h4>
                            {% endif %}
                            <div class="mt-3 text-center">
                                
                                {% if type == "list" %}
                                    <a class="btn btn-primary waves-effect waves-light" href="{% url 'Workers:WorkerCreate' %}" data-toggle="modal" data-target="#action_modal">اضافة بيانات</a>
                                {% endif %}
                                    
                            </div>
                        </div>
                    </div>
                </div>
                
                <div class="row d-flex justify-content-center">
                    <div class="col-lg-12 d-flex justify-content-center ">
                
                        <img src="/static/assets/images/error-img.png" width="400px" height="188px" alt="" class="img-fluid" >
                
                    </div>
                </div>

                {% endif %}

          </div>
      </div>
  </div>
{% endblock main %}

Workers/templates/Worker/worker_production_div.html
<div class="table-responsive scroll">
  <table
    class="table prod_pag table-centered table-dark table-nowrap text-center"
  >
    <thead>
      <tr>
        <th>م</th>
        <th>التاريخ</th>
        <th>اليوم</th>
        <th>الكمية بالقطعة</th>
          <th>المنتج</th>
          <th>فئة السعر</th>
          <th>الإجمالي</th>
        <th>المسؤول</th>
          {% if request.user.is_superuser %}
        <th><i class="fas fa-cogs"></i></th>
          {% endif %}
      </tr>
    </thead>
    <tbody>
        {% if production %}
          {% for x in production %}
          <tr style="text-align: center">
              <td>{{forloop.counter}}</td>
              <td>
              <span class="badge badge-danger"
                  >
                  {{x.date|date:'Y-m-d'}}</span
              >
              </td>
            <td>
               {{x.day}}
              </td>
              <td>
               {{x.quantity|floatformat:0}}
              </td>
                <td>
               {% if x.product %}
                 {{x.product}}
                {% else %}
                    -
                {% endif %}
              </td>
                <td>
               {{x.price|floatformat:2}}
              </td>
                <td>
               {{x.total|floatformat:2}}
              </td>
              <td>{{x.admin}}</td>
              {% if request.user.is_superuser %}
              <td>

              <!--
{#              <a#}
{#                  href="{% url 'Workers:WorkerProductionUpdate' x.id %}"#}
{#                  class="mr-3 text-warning"#}
{#                  data-toggle="modal"#}
{#                  data-target="#action_modal"#}
{#                  data-original-title="Edit"#}
{#                  ><i class="mdi mdi-pencil font-size-18"></i#}
{#              ></a>#} -->
              <a
                  onclick="
                          var result = confirm('هل أنت متأكد من الحذف؟');
                            if (result) {
                                WorkerProductionDelete('{{x.id}}')
                            }
                          "
                  style="cursor: pointer"
                  class="text-danger"
                  ><i class="mdi mdi-close font-size-18"></i
              ></a>

              </td>
              {% endif %}
              
          </tr>
          {% endfor %}
        {% endif %}
    </tbody>
  </table>
</div>

<div class="row text-center prod_pagination">
    <div class="col-md-12">
        <button class="btn btn-dark prod_prev">السابق</button>
        <span class="prod_page"></span>
        <button class="btn btn-dark prod_next">التالي</button>
    </div>
</div>
<br>

<div style="margin-top: 10px">
  <div class="row">
   
    <div class="col-lg-6 flex-center">
      <div class="card mini-stats-wid mb-0">
        <div class="card-body bg-danger">
          <div class="d-flex flex-wrap">
            <div class="">
              <h5 class="mb-2 text-light">
                اجمالي الإنتاج 
              </h5>
              <h3 class="mb-0 text-dark">
                
                {% if production_total %}
                {{production_total|floatformat:0}} قطعة
                {% else %}
                0 قطعة
                {% endif %}
              
              </h3>
            </div>

            <div class="avatar-sm ml-auto">
              <div
                class="avatar-title bg-light rounded-circle text-dark font-size-20"
              >
              <i class="fas fa-calculator"></i>               
               </div>
            </div>
          </div>
        </div>
      </div>
    </div>

    

    <div class="col-lg-6 flex-center">
      <div class="card mini-stats-wid mb-0">
        <div class="card-body bg-danger">
          <div class="d-flex flex-wrap">
            <div class="">
              <h5 class="mb-2 text-light">
                اجمالي الحساب المستحق
              </h5>
              <h3 class="mb-0 text-dark">
                
                {% if production_cost %}
                  {{production_cost|floatformat:2}} جنية
                {% else %} 
                  0.00 جنية
                {% endif %}

              </h3>
            </div>

            <div class="avatar-sm ml-auto">
              <div
                class="avatar-title bg-light rounded-circle text-dark font-size-20"
              >
              <i class="fas fa-dollar-sign"></i>                
               </div>
            </div>
          </div>
        </div>
      </div>
    </div>

  </div>
</div>

<script>
    $(document).ready(function() {
      var itemsPerPage = 10;
      var currentPage = 1;

      function showItems() {
        var startIndex = (currentPage - 1) * itemsPerPage;
        var endIndex = startIndex + itemsPerPage;

        $('.prod_pag tbody tr').hide();
        $('.prod_pag tbody tr').slice(startIndex, endIndex).show();
        $('.prod_page').empty();

        var totalItems = $('.prod_pag tbody tr').length;
        var totalPages = Math.ceil(totalItems / itemsPerPage);

        $('.prod_prev').prop('disabled', currentPage === 1);
        $('.prod_next').prop('disabled', currentPage === totalPages);

        for (var i = 1; i <= totalPages; i++) {
          var pageButton = $('<button>').text(i);
          pageButton.addClass('btn');
          if (i === currentPage) {
            pageButton.addClass('active bg-warning');
          }
          pageButton.click(function() {
            currentPage = parseInt($(this).text());
            showItems();
          });
          $('.prod_page').append(pageButton);
        }
      }

      $('.prod_prev').click(function() {
        if (currentPage > 1) {
          currentPage--;
          showItems();
        }
      });

      $('.prod_next').click(function() {
        var totalItems = $('.prod_pag tbody tr').length;
        var totalPages = Math.ceil(totalItems / itemsPerPage);

        if (currentPage < totalPages) {
          currentPage++;
          showItems();
        }
      });

      showItems();
    });
  </script>