Auth/urls.py
from django.urls import path
from .views import *

app_name = "Auth"
urlpatterns = [
    path('users/login/', Login.as_view(), name='login'),
    path('logout/', Logout.as_view(), name='logout'),
    path('ChangePassword/', ChangePassword, name='ChangePassword'),
    path('AddNewUser/', create_user, name='create_user'),
    path('Users/', Users.as_view(), name='Users'),
    path('Users/<int:pk>/update/', UsersUpdate.as_view(), name='UsersUpdate'),
]

Factories/urls.py
from django.urls import path
from .views import * 

app_name = 'Factories'
urlpatterns = [
    path('list/', FactoryList.as_view(), name="FactoryList"),
    path('trach/', FactoryTrachList.as_view(), name="FactoryTrachList"),
    path('create/', FactoryCreate.as_view(), name="FactoryCreate"),
    path('details/<int:pk>', FactoryDetails.as_view(), name="FactoryDetails"),
    path('update/<int:pk>', FactoryUpdate.as_view(), name="FactoryUpdate"),
    path('delete/<int:pk>', FactoryDelete.as_view(), name="FactoryDelete"),
    path('restore/<int:pk>', FactoryRestore.as_view(), name="FactoryRestore"),
    path('superDelete/<int:pk>', FactorySuperDelete.as_view(), name="FactorySuperDelete"),
    path('all/print/<int:pk>/', PrintAll, name="PrintAll"),
    path('get_product_weight_time/', get_product_weight_time, name="get_product_weight_time"),
    path('FactoryOutSide_color_filter/', FactoryOutSide_color_filter, name="FactoryOutSide_color_filter"),

    path('detail/payment/<int:pk>/div/', FactoryPayment_div.as_view(), name="FactoryPayment_div"),
    path('payment/create/', FactoryPaymentCreate, name="FactoryPaymentCreate"),
    path('payment/delete/', FactoryPaymentDelete, name="FactoryPaymentDelete"),
    path('payment/print/<int:pk>/', PrintPayment, name="PrintPayment"),
    
    path('detail/returned/<int:pk>/div/', FactoryReturned_div.as_view(), name="FactoryReturned_div"),
    path('returned/create/', FactoryReturnedCreate, name="FactoryReturnedCreate"),
    path('returned/delete/', ReturnedDelete, name="ReturnedDelete"),
    path('returned/print/<int:pk>/', PrintReturned, name="PrintReturned"),

    path('outside/<int:pk>/div/', FactoryOutSide_div.as_view(), name="FactoryOutSide_div"),
    path('outside/create/', FactoryOutSideCreate, name="FactoryOutSideCreate"),
    path('outside/delete/', FactoryOutsideDelete, name="FactoryOutsideDelete"),
    path('outside/print/<int:pk>/', PrintOutside, name="PrintOutside"),
    
    path('inside/<int:pk>/div/', FactoryInSide_div.as_view(), name="FactoryInSide_div"),
    path('inside/create/', FactoryInSideCreate, name="FactoryInSideCreate"),
    path('inside/delete/', FactoryInsideDelete, name="FactoryInsideDelete"),
    path('inside/print/<int:pk>/', PrintInside, name="PrintInside"),
    path('factory_outside_loss/<int:pk>/', UpdateFactoryOutsideLoss, name="UpdateFactoryOutsideLoss"),
    path('factory_inside_hour/<int:pk>/', UpdateFactoryHourPrice, name="UpdateFactoryHourPrice"),

    ########################################################

    path('SupplierList/<int:type>/', SupplierList.as_view(), name="SupplierList"),
    path('SupplierTrashList/<int:type>/', SupplierTrashList.as_view(), name="SupplierTrashList"),
    path('SupplierCreate/<int:type>/', SupplierCreate.as_view(), name="SupplierCreate"),
    path('SupplierUpdate/<int:pk>/', SupplierUpdate.as_view(), name="SupplierUpdate"),
    path('SupplierDelete/<int:pk>/', SupplierDelete.as_view(), name="SupplierDelete"),
    path('SupplierRestore/<int:pk>/', SupplierRestore.as_view(), name="SupplierRestore"),
    path('SupplierSuperDelete/<int:pk>/', SupplierSuperDelete.as_view(), name="SupplierSuperDelete"),

    path('SupplierQuantity/<int:pk>/', SupplierQuantityDetail, name="SupplierQuantity"),
    path('AddSupplierQuantity/<int:pk>/', AddSupplierQuantity, name="AddSupplierQuantity"),
    path('DelSupplierQuantity/<int:pk>/', DelSupplierQuantity, name="DelSupplierQuantity"),
   

    path('SupplierPayment/<int:pk>/', SupplierPaymentDetail, name="SupplierPayment"),
    path('AddSupplierPayment/<int:pk>/', AddSupplierPayment, name="AddSupplierPayment"),
    path('DelSupplierPayment/<int:pk>/', DelSupplierPayment, name="DelSupplierPayment"),
    path('supplier/all/print/<int:pk>/', PrintSupplierAll , name="PrintSupplierAll"),
    
    path('ProductQuantityInsideCreate/<int:pk>/', ProductQuantityInsideCreate, name="ProductQuantityInsideCreate"),
    path('DelProductQuantity/<int:pk>/', DelProductQuantity, name="DelProductQuantity"),
]

ZerOne/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from django.urls.conf import include
from django.conf.urls import url

urlpatterns = [
    path('01admin01/', admin.site.urls),
    path('admin/', include('Core.urls')),
    path('', include('Core.urls')),
    path('',include('Auth.urls')),
    path('factory/', include('Factories.urls')),
    path('product/', include('Products.urls')),
    path('worker/', include('Workers.urls')),
    path('treasury/', include('Treasury.urls')),
    path('wool/', include('Wool.urls')),
    path('invoices/',include('Invoices.urls'), ),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


Factories/models.py
from datetime import date
from Wool.models import Wool
from django.db import models
from Auth.models import User
from Core.models import Color
from Products.models import Product

# Create your models here.

class Factory(models.Model):
    created = models.DateTimeField(auto_now_add=True, verbose_name="تاريخ الاضافة")
    name = models.CharField(max_length=50, verbose_name="اسم المصنع")
    hour_price = models.FloatField(null=True, blank=True, verbose_name="حساب الساعه")
    machine_type = models.CharField(null=True, blank=True, max_length=50, verbose_name="نوع المكن")
    machine_count = models.IntegerField(null=True, blank=True, verbose_name="عدد المكن")
    phone = models.CharField(null=True, blank=True, max_length=12, verbose_name="رقم الهاتف")
    active = models.BooleanField(default=True, verbose_name="يعمل")
    start_date = models.DateField(null=True, blank=True, verbose_name="تاريخ البداية", default=date.today)
    deleted = models.BooleanField(default=False)
    
    def __str__(self):
        return self.name
    
class Payment(models.Model):
    created = models.DateTimeField(auto_now_add=True, verbose_name="تاريخ الاضافة")
    price = models.FloatField(verbose_name="المبلغ")
    factory = models.ForeignKey(Factory, on_delete=models.CASCADE, verbose_name="المصنع")
    recipient = models.CharField(max_length=50, null=True, blank=True, verbose_name="المستلم")
    admin = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, verbose_name="المسئول")
    date = models.DateField(null=True, verbose_name="التاريخ", default=date.today)
    
    def __str__(self):
        return self.factory.name
    
    
class FactoryReturned(models.Model):
    created = models.DateTimeField(auto_now_add=True, verbose_name="تاريخ الاضافة")
    item_count = models.FloatField(verbose_name="العدد")
    factory = models.ForeignKey(Factory, on_delete=models.CASCADE, verbose_name="المصنع")
    product = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name="الموديل")
    item_price = models.FloatField(verbose_name="سعر القطعة")
    total_price = models.FloatField(verbose_name="اجمالي السعر")
    admin = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, verbose_name="المسئول")
    date = models.DateField(null=True, verbose_name="التاريخ", default=date.today)
    returned_details = models.TextField(null=True, blank=True, verbose_name='التفاصيل')
    
    def __str__(self):
        return self.factory.name
    
WOOL_TYPE = (
    (1,"قطن"),
    (2,"صوف"),
    (3,"عجينة"),
    (4,"سبن"),
    (5,"لكرة"),
    (6,"رمش"),
    (7,"عصب"),
    (8,"بلستر"),
    (9,"استك"),
)    
         

class FactoryOutSide(models.Model):
    created = models.DateTimeField(auto_now_add=True, verbose_name="تاريخ العملية")
    date = models.DateField(null=True, verbose_name="التاريخ", default=date.today)
    factory = models.ForeignKey(Factory, on_delete=models.CASCADE, verbose_name="المصنع")
    wool = models.ForeignKey(Wool, on_delete=models.SET_NULL, null=True, verbose_name="الخامة")
    wool_count_item = models.FloatField(verbose_name="عدد الشكاير")
    color = models.ForeignKey(Color, on_delete=models.SET_NULL, null=True, verbose_name="اللون")
    weight = models.FloatField(null=True, verbose_name="الوزن بالكيلو")
    percent_loss = models.FloatField(null=True, verbose_name="الهالك (نسبة مؤية)")
    weight_after_loss = models.FloatField(null=True, verbose_name="الوزن بعد الهالك")
    admin = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, verbose_name="المسئول")
    
    def __str__(self):
        return self.factory.name


PRODUCT_TYPE = (
    
    (1,"صدر"),
    (2,"ضهر"),
    (3,"كم"),
    (4,"لياقة"),
)    
     
class FactoryInSide(models.Model):
    created = models.DateTimeField(auto_now_add=True, verbose_name="تاريخ العملية")
    date = models.DateField(null=True, verbose_name="التاريخ", default=date.today)
    factory = models.ForeignKey(Factory, on_delete=models.CASCADE, verbose_name="المصنع")
    color = models.ForeignKey(Color, null=True, on_delete=models.SET_NULL, verbose_name="اللون")
    product = models.ForeignKey(Product, on_delete=models.SET_NULL, null=True, verbose_name="الموديل")
    weight = models.FloatField(null=True, verbose_name="الوزن بالكيلو")
    product_weight = models.FloatField(null=True, verbose_name="وزن الموديل جرام")
    product_time = models.FloatField(null=True, verbose_name="زمن الموديل دقائق")
    product_count = models.IntegerField(null=True, verbose_name="عدد الموديل")
    # product_type = models.IntegerField(choices=PRODUCT_TYPE, null=True, blank=True, verbose_name="نوع القطع")
    wool_type = models.IntegerField(choices=WOOL_TYPE, null=True, blank=True, verbose_name="نوع الخامة")
    hour_count = models.FloatField(null=True, verbose_name="عدد الساعات")
    hour_price = models.FloatField(null=True, verbose_name="سعر الساعة")
    total_account = models.FloatField(null=True, verbose_name="اجمالي الحساب")
    admin = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, verbose_name="المسئول")
    
    def __str__(self):
        return self.factory.name


Fact_Type = (
    (1, "مصنع مورد"),
    (2, "مصنع مستورد"),
    )


class Supplier(models.Model):
    created = models.DateTimeField(auto_now_add=True, verbose_name="تاريخ الاضافة")
    name = models.CharField(max_length=50, verbose_name="الاسم")
    phone = models.CharField(max_length=11, null=True, blank=True, verbose_name='رقم الهاتف')
    address = models.CharField(max_length=250, verbose_name='العنوان', null=True, blank=True)
    type = models.IntegerField(choices=Fact_Type, default=0, verbose_name="نوع المصنع")
    deleted = models.BooleanField(default=False)

    def __str__(self):
        return self.name


class SupplierQuantity(models.Model):
    created = models.DateTimeField(auto_now_add=True, verbose_name="تاريخ العملية")
    date = models.DateField(null=True, verbose_name="التاريخ", default=date.today)
    supplier = models.ForeignKey(Supplier, on_delete=models.CASCADE, verbose_name="المورد/المستورد")
    product = models.ForeignKey(Product, on_delete=models.SET_NULL, null=True, verbose_name="الموديل")
    product_count = models.FloatField(default=0, verbose_name="عدد القطع")
    product_price = models.FloatField(default=0.0, verbose_name="سعر القطعة")
    total_account = models.FloatField(default=0.0, verbose_name="اجمالي الحساب")
    admin = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, verbose_name="المسؤل")

    def __str__(self):
        return self.supplier.name


class SupplierPayment(models.Model):
    created = models.DateTimeField(auto_now_add=True, verbose_name="تاريخ العملية")
    date = models.DateField(null=True, verbose_name="التاريخ", default=date.today)
    supplier = models.ForeignKey(Supplier, on_delete=models.CASCADE, verbose_name="المورد/المستورد")
    value = models.FloatField(default=0.0, verbose_name="المبلغ")
    reason = models.CharField(max_length=250, null=True, blank=True, verbose_name='الوصف/السبب')
    admin = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, verbose_name="المسؤل")

    def __str__(self):
        return self.supplier.name   
    

class ProductQuantityInside(models.Model):
    date = models.DateField(null=True, verbose_name="التاريخ", default=date.today)
    product_item = models.ForeignKey(Product, on_delete=models.SET_NULL, null=True, verbose_name="الموديل")
    factory_item = models.ForeignKey(Factory, on_delete=models.SET_NULL, null=True, verbose_name='المصنع')
    product_count = models.IntegerField(null=True, blank=True, verbose_name='الكمية')
    product_color = models.ForeignKey(Color, on_delete=models.SET_NULL, null=True, verbose_name='اللون')
    created_user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, verbose_name='المستخدم')
    
    def __str__(self):
        return self.product_item.name

Factories/templates/Factory/factory_payment.html
{% load crispy_forms_tags %}

<div class="row">
  <div class="col-lg-12">
<div class="card">
<div class="card-body">
<!-- مسحوبات المصنع -->
<div class="tab-pane" id="processing_payment" role="tabpanel">
<div class="row">
<div class="col-lg-12">

{% if factory.deleted == 0 %}
<div class="table-responsive" id="order_list">
<table class="table table-nowrap table-borderless">
<thead>
<form>
<tr>
<th
class="col-lg-3 col-xl-3 col-md-3"
style="width: 20%"
>
{{payment_form.date|as_crispy_field}}
</th>
<th
class="col-lg-3 col-xl-3 col-md-3"
style="width: 30%"
>
{{payment_form.price|as_crispy_field}}
</th>
<th
class="col-lg-3 col-xl-3 col-md-3"
style="width: 50%"
>
{{payment_form.recipient|as_crispy_field}}
</th>

<th class="col-lg-1 col-xl-1 col-md-1">
<a
  style="width: 100%"
  onclick="PaymentCreate()"
  class="btn btn-success"
>
<i class="fas fa-plus-circle"></i>
  اضافة
</a>
</th>
</tr>
</form>
</thead>
</table>
</div>
{% endif %}
<style>
/*.table-responsive {*/
/*max-height: 500px;*/
/*}*/

/*.scroll{*/
    /*overflow-y: scroll;*/
    /*overflow-x: scroll;*/
/*}*/
/*.table-responsive::-webkit-scrollbar {*/
/*display: none;*/
/*}*/
</style>

<div class="table-responsive">
    <table class="table table-centered table-dark table-nowrap text-center">
        <thead>
            <tr>
                <td style="width: 30%">
                    <input type="date" class="form-control" id="pay_specific_date" style="width: 100%" onchange="PayDateFilter(this)">
                </td>
            </tr>
        </thead>
    </table>
</div>

<div id="paymnet">
<div class="table-responsive scroll">
<table
class="table pag table-centered table-dark table-nowrap text-center"
>
<thead>
<tr>
<th>م</th>
<th>التاريخ</th>
<th>المبلغ</th>
<th>المستلم</th>
<th>المسؤول</th>
{% if request.user.is_superuser %}
<th><i class="fas fa-cogs"></i></th>
{% endif %}
</tr>
</thead>
<tbody>
{% for x in payment %}
<tr style="text-align: center">
<td>{{forloop.counter}}</td>
<td>
<span  style="font-size: 16px" >
  <i class="fas fa-calendar-alt"></i>
  {{x.date|date:'Y-m-d'}}</span>

</td>
<td>
<i class="fas fa-dollar-sign"></i> {{x.price|floatformat:2}}
</td>
<td><i class="fas fa-user"></i> {{x.recipient}}</td>
<td><i class="fas fa-user-tie"></i> {{x.admin}}</td>
{% if request.user.is_superuser %}
<td>

<!--
{#                            <a#}
{#                              href="{% url 'Factories:FactoryPaymentUpdate' x.id %}"#}
{#                              class="mr-3 text-warning"#}
{#                              data-toggle="modal"#}
{#                              data-target="#action_modal"#}
{#                              data-original-title="Edit"#}
{#                              ><i class="mdi mdi-pencil font-size-18"></i#}
{#                            ></a>#}-->
<a
  onclick="
          var result = confirm('هل أنت متأكد من الحذف؟');
            if (result) {
                PaymentDelete('{{x.id}}')
            }
          "
  style="cursor: pointer"
  class="text-danger"
  ><i class="mdi mdi-close font-size-18"></i
></a>
</td>
{% endif %}

</tr>
{% endfor %}
</tbody>
</table>
</div>

<div class="row text-center pagination">
    <div class="col-md-12">
        <button class="btn btn-dark prev">السابق</button>
        <span class="page"></span>
        <button class="btn btn-dark next">التالي</button>
    </div>
</div>
<br>

<div style="margin-top: 10px">
<div class="row">
<div class="col-lg-4">
<div class="card mini-stats-wid mb-0">
<div class="card-body bg-danger">
<div class="d-flex flex-wrap">
  <div class="mr-3">
    <h5 class="mb-2 text-light">الحساب المستحق</h5>
    <h5 class="mb-0 text-dark">
        {% if total_account %}
        {{total_account|floatformat:2}}
        {% else %}
        0.00
        {% endif %}
        جنية
    </h5>
  </div>

  <div class="avatar-xs ml-auto">
    <div
      class="avatar-title bg-light rounded-circle text-dark font-size-20"
    >
      <i class="fas fa-dollar-sign"></i>
    </div>
  </div>
</div>
</div>
</div>
</div>
<div class="col-lg-4">
<div class="card mini-stats-wid mb-0">
<div class="card-body bg-danger">
<div class="d-flex flex-wrap">
  <div class="">
    <h5 class="mb-2 text-light">
      اجمالي المسحوبات
    </h5>
    <h5 class="mb-0 text-dark">
        {% if payment_sum %}
        {{payment_sum|floatformat:2}}
        {% else %}
        0.00
        {% endif %}
        جنية
    </h5>
  </div>

  <div class="avatar-xs ml-auto">
    <div
      class="avatar-title bg-light rounded-circle text-dark font-size-20"
    >
      <i class="fas fa-hand-holding-usd"></i>
    </div>
  </div>
</div>
</div>
</div>
</div>
<div class="col-lg-4">
<div class="card mini-stats-wid mb-0">
<div class="card-body bg-danger">
<div class="d-flex flex-wrap">
  <div class="">
    <h5 class="mb-2 text-light">باقي الحساب</h5>
    <h5 class="mb-0 text-dark">
        {% if total %}
        {{total|floatformat:2}}
        {% else %}
        0.00
        {% endif %}
        جنية
    </h5>
  </div>

  <div class="avatar-xs ml-auto">
    <div
      class="avatar-title bg-light rounded-circle text-dark font-size-20"
    >
      <i class="fas fa-file-invoice-dollar"></i>
    </div>
  </div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>

<script>
function PaymentCreate() {
$.ajax({
type: "POST",
url: "{% url 'Factories:FactoryPaymentCreate'  %}",
data: {
id: "{{object.id}}",
date: $("#date").val(),
price: $("#price").val(),
recipient: $("#recipient").val(),
csrfmiddlewaretoken: "{{ csrf_token }}",
dataType: "json",
},
success: function (response) {
/* response message */
if (response.msg == 1) {
$("#price").val("");
$("#recipient").val("");
$("#paymnet").html("&nbsp;").load("{% url 'Factories:FactoryPayment_div' object.id %}");
alert("تم الاضافة بنجاح");
$( '#inside' ).html( '&nbsp;' ).load( "{% url 'Factories:FactoryInSide_div' object.id %}");
$('#outside').html('&nbsp;').load("{% url 'Factories:FactoryOutSide_div' object.id %}");
$('#returned').html('&nbsp;').load("{% url 'Factories:FactoryReturned_div' object.id %}");

} else {
alert("حاول مرة اخري / خطأ في البيانات");
}
},

failure: function () {},
});
}

function PaymentDelete(payment_id) {
$.ajax({
type: "POST",
url: "{% url 'Factories:FactoryPaymentDelete' %}",
data: {
payment_id: payment_id,
csrfmiddlewaretoken: "{{ csrf_token }}",
dataType: "json",
},
success: function (data) {
/* response message */
$("#paymnet")
.html("&nbsp;")
.load(
"{% url 'Factories:FactoryPayment_div' object.id %}"
);
alert("تم الحذف بنجاح");
$( '#inside' ).html( '&nbsp;' ).load( "{% url 'Factories:FactoryInSide_div' object.id %}");
$('#outside').html('&nbsp;').load("{% url 'Factories:FactoryOutSide_div' object.id %}");
$('#returned').html('&nbsp;').load("{% url 'Factories:FactoryReturned_div' object.id %}");
},

failure: function () {},
});
}
</script>
<script>
    function PayDateFilter(val) {
        if (val.value){
            val.style.backgroundColor = 'lightgreen';
        }
        else {
            val.style.backgroundColor = '';
        }
        date_val = val.value;
        $( '#paymnet' ).html( '&nbsp;' ).load( "{% url 'Factories:FactoryPayment_div' object.id %}?date_val=" + date_val );
    };
</script>

</div>
</div>
</div>
</div>
</div>
</div>
</div>