Auth/urls.py
from django.urls import path
from .views import *

app_name = "Auth"
urlpatterns = [
    path('users/login/', Login.as_view(), name='login'),
    path('logout/', Logout.as_view(), name='logout'),
    path('ChangePassword/', ChangePassword, name='ChangePassword'),
    path('AddNewUser/', create_user, name='create_user'),
    path('Users/', Users.as_view(), name='Users'),
    path('Users/<int:pk>/update/', UsersUpdate.as_view(), name='UsersUpdate'),
]

Core/urls.py
from django.urls import path 
from . import views

app_name = 'Core'
urlpatterns = [
    path('', views.Index, name='index'),
    path('systemInfoCreate/', views.SystemInfoCreate.as_view(), name='SystemInfoCreate'),
    path('ColorCreate/', views.ColorCreate.as_view(), name='ColorCreate'),
    path('ColorUpdate/<int:pk>/', views.ColorUpdate.as_view(), name='ColorUpdate'),
    path('ColorDelete/<int:pk>/', views.ColorDelete.as_view(), name='ColorDelete'),
    path('ColorList/', views.ColorList.as_view(), name='ColorList'),
    path('ExpensessTypeList/', views.ExpensessTypeList.as_view(), name='ExpensessTypeList'),
    path('ExpensessTypeCreate/', views.ExpensessTypeCreate.as_view(), name='ExpensessTypeCreate'),
    path('ExpensessTypeDelete/<int:pk>/', views.ExpensessTypeDelete.as_view(), name='ExpensessTypeDelete'),
    path('systemInfoUpdate/<int:pk>/', views.SystemInfoUpdate.as_view(), name='SystemInfoUpdate'),
    path('factory_search/', views.FactorySearch.as_view(), name='FactorySearch'),
    path('product_search/', views.ProductSearch.as_view(), name='ProductSearch'),
    path('ProductSearch_size/', views.ProductSearch_size.as_view(), name='ProductSearch_size'),
    path('seller_search/', views.SellerSearch.as_view(), name='SellerSearch'),
    path('worker_search/', views.WorkerSearch.as_view(), name='WorkerSearch'),
    path('invoice_search/', views.InvoiceSearch.as_view(), name='InvoiceSearch'),
    path('treasury_search/', views.TreasurySearch.as_view(), name='TreasurySearch'),
    path('sp_invoice_search/<int:type>/', views.SpInvoiceSearch.as_view(), name='SpInvoiceSearch'),
    path('sp_supplier_search/<int:type>/', views.SpSupplierSearch.as_view(), name='SpSupplierSearch'),
    path('seller_invoice_search/<int:type>/', views.SellerInvoiceSearch.as_view(), name='SellerInvoiceSearch'),
    path('client_invoice_search/<int:type>/', views.ClientInvoiceSearch.as_view(), name='ClientInvoiceSearch'),
    path('wool_supplier_search/', views.WoolSupplierSearch.as_view(), name='WoolSupplierSearch'),
    path('wool_search/', views.WoolSearch.as_view(), name='WoolSearch'),
    path('system_statistics/', views.SystemStatistics, name='system_statistics'),
    path('ExpensessDetail/', views.ExpensessDetail, name='ExpensessDetail'),
    path('ExpensessCreate/', views.ExpensessCreate, name='ExpensessCreate'),
    path('ExpensessDelete/<int:pk>/', views.ExpensessDelete.as_view(), name='ExpensessDelete'),
]

Treasury/urls.py
from django.urls import path
from .views import *

app_name ="Treasury"
urlpatterns = [
    path('list/', TreasuryList.as_view(), name="TreasuryList"),
    path('trach/', TreasuryTrachList.as_view(), name="TreasuryTrachList"),
    path('create/', TreasuryCreate.as_view(), name="TreasuryCreate"),
    path('update/<int:pk>/', TreasuryUpdate.as_view(), name="TreasuryUpdate"),
    path('details/<int:pk>/', TreasuryDetails.as_view(), name="TreasuryDetails"),
    path('details_div/<int:pk>/', TreasuryOperationDiv.as_view(), name="TreasuryOperationDiv"),
    path('delete/<int:pk>', TreasuryDelete.as_view(), name="TreasuryDelete"),
    path('restore/<int:pk>', TreasuryRestore.as_view(), name="TreasuryRestore"),
    path('superDelete/<int:pk>', TreasurySuperDelete.as_view(), name="TreasurySuperDelete"),
    path('create/operation_in/<int:pk>/', OperationInCreate.as_view(), name="OperationInCreate"),
    path('creat/operation_out/<int:pk>/', OperationOutCreate.as_view(), name="OperationOutCreate"),
    path('opertation_superDelete/<int:pk>/', OperationSuperDelete.as_view(), name="OperationSuperDelete"),
    path('treasury_report/<int:pk>/', TreasuryReport, name="TreasuryReport"),
]

ZerOne/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from django.urls.conf import include
from django.conf.urls import url

urlpatterns = [
    path('01admin01/', admin.site.urls),
    path('admin/', include('Core.urls')),
    path('', include('Core.urls')),
    path('',include('Auth.urls')),
    path('factory/', include('Factories.urls')),
    path('product/', include('Products.urls')),
    path('worker/', include('Workers.urls')),
    path('treasury/', include('Treasury.urls')),
    path('wool/', include('Wool.urls')),
    path('invoices/',include('Invoices.urls'), ),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


Treasury/models.py
from django.db.models.signals import post_save
from django.db import models
from django.dispatch import receiver
from Auth.models import User
from datetime import date


class Treasury(models.Model):
    name = models.CharField(max_length=100, verbose_name="اسم الخزنة")
    date = models.DateTimeField(auto_now_add=True, verbose_name="تاريخ الاضافة")
    balance = models.FloatField(default=0.00, verbose_name="رصيد الخزنة")
    deleted = models.BooleanField(default=False)

    def __str__(self):
        return self.name
    

OPERATION_TYPE = (
    (1, "اضافة رصيد"),
    (2, "سحب رصيد")
)

class TreasuryOperation(models.Model):
    treasury = models.ForeignKey(Treasury, on_delete=models.CASCADE,null=True, blank=True, verbose_name="الخزنة")
    operation_type = models.IntegerField(choices=OPERATION_TYPE, default=0, verbose_name="نوع العملية")
    operation_value = models.FloatField(default=0.0, verbose_name="قيمة العملية")
    operation_description = models.TextField(max_length=200, null=True, blank=True, verbose_name="وصف العملية")
    operation_user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True, verbose_name="انشاء بواسطة")
    operation_date = models.DateTimeField(default=date.today, verbose_name="تاريخ العملية")
    deleted_operation = models.BooleanField(default=False)

    def __str__(self):
        return self.treasury.name
    

# signals function to create operation when user created new treasury 
@receiver(post_save, sender=Treasury)
def create_treasury_operatoin(sender, instance, created, **kwargs):
    if created:
        import inspect
        for frame_record in inspect.stack():
            if frame_record[3] == 'get_response':
                request = frame_record[0].f_locals['request']
                break
        else:
            request = None

        if instance.balance > 0:
            TreasuryOperation.objects.create(
                treasury=instance,
                operation_type=1,
                operation_value=instance.balance,
                operation_description="قيمة افتتاحية",
                operation_user=request.user
                )

Treasury/views.py
from django.shortcuts import render
from django.shortcuts import redirect
from django.urls import reverse, reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import *
from .forms import *
from django.contrib import messages
import weasyprint
from django.template.loader import render_to_string
from .models import *
from Core.models import SystemInformation
from datetime import datetime
from django.http import HttpResponse
from django.db.models.aggregates import Sum


class TreasuryList(LoginRequiredMixin, ListView):
    login_url = '/auth/login/'
    model = Treasury
    paginate_by = 12
    template_name = 'Treasury/treasury_list.html'
    
    def get_queryset(self):
        qureyset = self.model.objects.filter(deleted=False).order_by('-id')
        return qureyset
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['type'] = 'list'
        context['title'] = 'قائمة الخزائن'
        context['icons'] = '<i class="fas fa-shapes"></i>'
        context['page'] = 'active'
        context['count'] = self.model.objects.filter(deleted=False).count()
        return context


class TreasuryTrachList(LoginRequiredMixin, ListView):
    login_url = '/auth/login'
    model = Treasury
    paginate_by = 12
    template_name = 'Treasury/treasury_list.html'
    
    def get_queryset(self):
        queyset = self.model.objects.filter(deleted=True).order_by('-id')
        return queyset
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['type'] = 'trach'
        context['count'] = self.model.objects.filter(deleted=True).count()
        return context


class TreasuryCreate(LoginRequiredMixin, CreateView):
    login_url = '/auth/login/'
    model = Treasury
    form_class = TreasuryForm
    template_name = 'forms/form_template.html'
    success_url = reverse_lazy('Treasury:TreasuryList')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'اضافة خزنة جديدة'
        context['message'] = 'add'
        context['action_url'] = reverse_lazy('Treasury:TreasuryCreate')
        return context
    
    # def post(self, request):
    #     if request.method == 'POST':
    #         form =self.form_class(request.POST or None)
    #         if form.is_valid():
    #             myform = form.save(commit=False)
    #             myform.treasury_user = request.user
    #             myform.save()
    #             return redirect(self.get_success_url())

    def get_success_url(self):
        messages.success(self.request, "تم اضافة خزنة جديدة بنجاح", extra_tags="success")

        if self.request.POST.get('url'):
            return self.request.POST.get('url')
        else:
            return self.success_url
    

class TreasuryUpdate(LoginRequiredMixin ,UpdateView):
    login_url = '/auth/login/'
    model = Treasury
    form_class = TreasuryFormUpdate
    template_name = 'forms/form_template.html'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'تعديل الخزنة: ' + str(self.object)
        context['message'] = 'update'
        context['action_url'] = reverse_lazy('Treasury:TreasuryUpdate', kwargs={'pk': self.object.id})
        return context
    
    def get_success_url(self):
        messages.success(self.request,  "تم تعديل الخزنة " + str(self.object) + " بنجاح ", extra_tags="success")
        if self.request.POST.get('url'):
            return self.request.POST.get('url')
        else:
            return self.success_url
                

class TreasuryDelete(LoginRequiredMixin ,UpdateView):
    login_url = '/auth/login/'
    model = Treasury
    form_class = TreasuryDeleteForm
    template_name = 'forms/form_template.html'

    def get_success_url(self):
        return reverse('Treasury:TreasuryList')
        
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'نقل الخزنة الي سلة المهملات: ' + str(self.object)
        context['message'] = 'delete'
        context['action_url'] = reverse_lazy('Treasury:TreasuryDelete', kwargs={'pk': self.object.id})
        return context

    def form_valid(self, form):
        messages.success(self.request, " تم نقل الخزنة " + str(self.object) + ' الي سلة المهملات بنجاح ' , extra_tags="success")
        myform = Treasury.objects.get(id=self.kwargs['pk'])
        myform.deleted = 1
        myform.save()
        return redirect(self.get_success_url())        


class TreasuryRestore(LoginRequiredMixin ,UpdateView):
    login_url = '/auth/login/'
    model = Treasury
    form_class = TreasuryDeleteForm
    template_name = 'forms/form_template.html'

    def get_success_url(self):
        return reverse('Treasury:TreasuryList')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'استرجاع الخزنة: ' + str(self.object)
        context['message'] = 'restore'
        context['action_url'] = reverse_lazy('Treasury:TreasuryRestore', kwargs={'pk': self.object.id})
        return context

    def form_valid(self, form):
        messages.success(self.request, " تم ارجاع الخزنة " + str(self.object) + ' الي القائمة بنجاح ' , extra_tags="success")
        myform = Treasury.objects.get(id=self.kwargs['pk'])
        myform.deleted = 0
        myform.save()
        return redirect(self.get_success_url())
    

class TreasurySuperDelete(LoginRequiredMixin, UpdateView):
    login_url = '/auth/login/'
    model = Treasury
    form_class = TreasuryDeleteForm
    template_name = 'forms/form_template.html'

    def get_success_url(self):
        return reverse('Treasury:TreasuryTrachList')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'حذف الخزنة : ' + str(self.object)
        context['message'] = 'super_delete'
        context['action_url'] = reverse_lazy('Treasury:TreasurySuperDelete', kwargs={'pk': self.object.id})
        return context

    def form_valid(self, form):
        messages.success(self.request, "تم حذف الخزنة " + str(self.object) + " نهائيا بنجاح ", extra_tags="success")
        my_form = Treasury.objects.get(id=self.kwargs['pk'])
        my_form.delete()
        return redirect(self.get_success_url())


class TreasuryDetails(LoginRequiredMixin, DetailView):
    login_url = '/auth/login/'
    model = Treasury
    template_name = 'Treasury/treasury_details.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['type'] = 'list'
        context['treasury'] = self.object
        context['form'] = TreasuryOperationForm
        tr = TreasuryOperation.objects.filter(treasury=self.object)
        context['treasury_operation_obj'] = tr.order_by('-operation_date', '-id')
        context['last_op'] = tr.last()
        context['total_deposit'] = TreasuryOperation.objects.filter(operation_type=1, treasury=self.object).aggregate(sum=Sum('operation_value')).get('sum')
        context['total_withdrawals'] = TreasuryOperation.objects.filter(operation_type=2, treasury=self.object).aggregate(sum=Sum('operation_value')).get('sum')

        return context


class TreasuryOperationDiv(LoginRequiredMixin, DetailView):
    login_url = '/auth/login/'
    model = Treasury
    template_name = 'Treasury/treasury_operation_div.html'

    def get_context_data(self, **kwargs):
        query_set = TreasuryOperation.objects.filter(treasury=self.object).order_by('-operation_date', '-id')
        date_val = self.request.GET.get('date_val')
        type_val = self.request.GET.get('type_val')

        if date_val:
            query_set = query_set.filter(operation_date=date_val)

        if type_val:
            query_set = query_set.filter(operation_type=int(type_val))

        context = super().get_context_data(**kwargs)
        context['type'] = 'list'
        context['treasury'] = self.object
        context['form'] = TreasuryOperationForm
        context['treasury_operation_obj'] = query_set
        context['last_op'] = TreasuryOperation.objects.filter(treasury=self.object).last()
        return context


class OperationInCreate(LoginRequiredMixin, CreateView):
    login_url = '/auth/login/'
    model = TreasuryOperation
    form_class = TreasuryOperationForm
    template_name = 'forms/form_template.html'

    def get_form_kwargs(self):
        kwargs = super(OperationInCreate, self).get_form_kwargs()
        kwargs['treasury_id'] = self.kwargs['pk']
        return kwargs

    def get_success_url(self):
        messages.success(self.request, "تم اضافة رصيد بنجاح", extra_tags="success")
        return reverse_lazy('Treasury:TreasuryDetails', kwargs={'pk': self.kwargs['pk']})
          
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'اضافة رصيد'
        context['message'] = 'add'
        context['action_url'] = reverse_lazy('Treasury:OperationInCreate',  kwargs={'pk': self.kwargs['pk']})
        return context
    
    def form_valid(self, form):
        form.save()
        obj = form.save(commit=False)
        myform = TreasuryOperation.objects.get(id=obj.id)
        myform.operation_user = self.request.user
        myform.treasury = Treasury.objects.get(id=self.kwargs['pk'])
        myform.operation_type = 1
        myform.save()

        myform2 = myform.treasury
        myform2.balance += myform.operation_value
        myform2.save(update_fields=['balance'])
        
        return redirect(self.get_success_url())



Treasury/templates/Treasury/treasury_operation.html
{% load crispy_forms_tags %}
{% load humanize %}
<div class="row">
        <div class="col-lg-12">
            <div class="card" >
                <div class="card-body">
                    <!-- الداخل المصنع -->
                    <div class="tab-pane" id="treasury_operation" role="tabpanel">
                        <div class="row">
                            <div class="col-lg-12">
                                <div class="table-responsive">
                                <table class="table table-centered table-dark table-nowrap text-center">
                                    <thead>
                                        <tr>
                                            <td style="width: 60%" class="op_sell">
                                                <select class="form-control" id="op_type" style="width: 100%" onchange="OpTypeFilter(this)">
                                                    <option disabled selected value="">عرض عمليات ايداع/سحب؟</option>
                                                    <option value=" ">كل العمليات</option>
                                                    <option value="1">إيداع</option>
                                                    <option value="2">سحب</option>
                                                </select>
                                            </td>
                                            <td style="width: 40%">
                                                <input type="date" class="form-control" id="op_date" min="{{ object.date|date:'Y-m-d' }}" style="width: 100%" onchange="OpDateFilter(this)">
                                            </td>
                                        </tr>
                                    </thead>
                                </table>
                            </div>
                                <div id="operatoin_data">
                                    <div class="table-responsive scroll" >
                                        <table class="table pag table-centered table-dark table-nowrap text-center">
                                            <thead >
                                                <tr>
                                                    <th>م</th>
                                                    <th>التاريخ</th>
                                                    <th>نوع العملية</th>
                                                    <th>قيمة العملية</th>
                                                    <th>وصف العملية</th>
                                                    <th>المسئول</th>
                                                    {% if request.user.is_superuser %}
                                                    {% if treasury.deleted == 0 %}
                                                    <th><i class="fas fa-cogs"></i></th>
                                                    {% endif %}
                                                    {% endif %}
                                                </tr>
                                            </thead>
                                            <tbody >
                                            {% for w in treasury_operation_obj  %}
                                                <tr style="text-align: center;">
                                                    <td>{{forloop.counter}}</td>
                                                    <td><span>{{w.operation_date|date:'Y-m-d'}}</span></td>
                                                    <td>
                                                        <span>
                                                            {% if w.operation_type == 1 %}
                                                            <i class='bx bx-chevrons-down' style="color: rgba(12, 186, 44, 0.827);"></i>
                                                            {% else %}
                                                            <i class='bx bx-chevrons-up' style="color: rgba(201, 12, 60, 0.827);"></i>
                                                            {% endif %}
                                                        "{{w.get_operation_type_display}}"
                                                        </span>
                                                    </td>
                                                    <td><span>{{w.operation_value|floatformat:2|intcomma}} جنية</span></td>
                                                    <td>
                                                        <span>
                                                            {% if w.operation_description %}
                                                                "{{w.operation_description}}"
                                                            {% else %}
                                                                "---"
                                                            {% endif %}
                                                        </span>
                                                    </td>
                                                    <td><i class="fas fa-user-tie"></i> {{w.operation_user}} </td>
                                                   {% if request.user.is_superuser %}
                                                    {% if treasury.deleted == 0 %}
                                                   <td>
                                                   {% if w.id == last_op.id %}
                                                    <a href="{% url 'Treasury:OperationSuperDelete' w.id %}" class="mr-3 text-warning"data-toggle="modal" data-target="#action_modal" data-original-title="Edit"><i class="mdi mdi-close font-size-18" style="cursor: pointer;"></i></a>
                                                   {% endif %}
                                                    </td>
                                                   {% endif %}
                                                   {% endif %}


                                                </tr>
                                            {% endfor %}
                                            </tbody>
                                        </table>
                                    </div>

                                    <div class="row text-center pagination">
                                        <div class="col-md-12">
                                            <button class="btn btn-dark prev">السابق</button>
                                            <span class="page"></span>
                                            <button class="btn btn-dark next">التالي</button>
                                        </div>
                                    </div>
                                    <br>
                                </div>
                                <script src="/static/assets/libs/jquery/jquery.min.js"></script>
                                <script>
                                    $(document).ready(function() {
                                        $('#op_type').select2();
                                    });
                                </script>
                                <script>
                                    function OpTypeFilter(val) {
                                        if (val.value && val.value!= ' '){
                                            $( '.op_sell' ).find('.select2-container').find('.select2-selection--single').css("background-color","lightgreen");
                                        }
                                        else {
                                            $( '.op_sell' ).find('.select2-container').find('.select2-selection--single').css("background-color","");
                                        }

                                        $( '#op_date' ).css("background-color","");
                                        $( '#op_date' ).val('');

                                        type_val = val.value;
                                        $( '#operatoin_data' ).html( '&nbsp;' ).load( "{% url 'Treasury:TreasuryOperationDiv' object.id %}?type_val=" + type_val );
                                    };
                                    function OpDateFilter(val) {
                                        if (val.value){
                                            val.style.backgroundColor = 'lightgreen';
                                        }
                                        else {
                                            val.style.backgroundColor = '';
                                        }

                                        $('#op_type').select2('destroy');
                                        $('#op_type').val('').select2();

                                        date_val = val.value;
                                        $( '#operatoin_data' ).html( '&nbsp;' ).load( "{% url 'Treasury:TreasuryOperationDiv' object.id %}?date_val=" + date_val );
                                    };
                                </script>
                            </div>
                        </div>

                 </div>

                </div>
            </div>
        </div>
    </div>

  

Treasury/templates/Treasury/treasury_operation_div.html
{% load humanize %}
<div class="table-responsive scroll">
    <table class="table op_pag table-centered table-dark table-nowrap text-center">
        <thead>
            <tr>
                <th>م</th>
                <th>التاريخ</th>
                <th>نوع العملية</th>
                <th>قيمة العملية</th>
                <th>وصف العملية</th>
                <th>المسئول</th>
                {% if treasury.deleted == 0 %}
                <th><i class="fas fa-cogs"></i></th>
                {% endif %}
            </tr>
        </thead>
        <tbody>
            {% for w in treasury_operation_obj %}
            <tr style="text-align: center;">
                <td>{{forloop.counter}}</td>
                <td><span>{{w.operation_date | date:'Y-m-d'}}</span></td>
                <td>
                    <span>
                        {% if w.operation_type == 1 %}
                        <i class='bx bx-chevrons-down' style="color: rgba(12, 186, 44, 0.827);"></i>
                        {% else %}
                        <i class='bx bx-chevrons-up' style="color: rgba(201, 12, 60, 0.827);"></i>
                        {% endif %}
                        "{{w.get_operation_type_display}}"
                    </span>
                </td>
                <td><span>{{w.operation_value|floatformat:2|intcomma}} جنية</span></td>
                <td>
                    <span>
                        {% if w.operation_description %}
                        "{{w.operation_description}}"
                        {% else %}
                        "---"
                        {% endif %}
                    </span>
                </td>
                <td><i class="fas fa-user-tie"></i> {{w.operation_user}} </td>
                {% if treasury.deleted == 0 %}
                {% if request.user.is_superuser %}
                <td>
                    {% if w.id == last_op.id %}
                    <a href="{% url 'Treasury:OperationSuperDelete' w.id %}" class="mr-3 text-warning"
                        data-toggle="modal" data-target="#action_modal" data-original-title="Edit"><i
                            class="mdi mdi-close font-size-18" style="cursor: pointer;"></i></a>
                    {% endif %}
                </td>
                {% endif %}
                {% endif %}


            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

<div class="row text-center op_pagination">
    <div class="col-md-12">
        <button class="btn btn-dark op_prev">السابق</button>
        <span class="op_page"></span>
        <button class="btn btn-dark op_next">التالي</button>
    </div>
</div>
<br>

<script>
    $(document).ready(function() {
      var itemsPerPage = 10;
      var currentPage = 1;

      function showItems() {
        var startIndex = (currentPage - 1) * itemsPerPage;
        var endIndex = startIndex + itemsPerPage;

        $('.op_pag tbody tr').hide();
        $('.op_pag tbody tr').slice(startIndex, endIndex).show();
        $('.op_page').empty();

        var totalItems = $('.op_pag tbody tr').length;
        var totalPages = Math.ceil(totalItems / itemsPerPage);

        $('.op_prev').prop('disabled', currentPage === 1);
        $('.op_next').prop('disabled', currentPage === totalPages);

        for (var i = 1; i <= totalPages; i++) {
          var pageButton = $('<button>').text(i);
          pageButton.addClass('btn');
          if (i === currentPage) {
            pageButton.addClass('active bg-warning');
          }
          pageButton.click(function() {
            currentPage = parseInt($(this).text());
            showItems();
          });
          $('.op_page').append(pageButton);
        }
      }

      $('.op_prev').click(function() {
        if (currentPage > 1) {
          currentPage--;
          showItems();
        }
      });

      $('.op_next').click(function() {
        var totalItems = $('.op_pag tbody tr').length;
        var totalPages = Math.ceil(totalItems / itemsPerPage);

        if (currentPage < totalPages) {
          currentPage++;
          showItems();
        }
      });

      showItems();
    });
  </script>